### ISSUE TITLE
Issue by team #176

### ISSUE THREAD

**Issue by Prabhakarzx** [chrystalme/private-events#6]
# Great work @chrystalme and @ahmetbozaci  :100: 
#### Here are a few suggestions which might make it more appealing! :1234: 
- [ ] Form UI can be improved 
- [ ] Readme can be more descriptive
- [ ] commits should be more descriptive

**Comment by chrystalme** [comment]
## Thanks @Prabhakarzx  we are off 🚀  to the ⏭️
